# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2],[3,4]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [3]:
a1.shape, a2.shape, a3.shape

((3,), (2, 2), (2, 2, 2))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 2), 2, dtype('int32'), 4, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 2), 3, dtype('int32'), 8, numpy.ndarray)

In [12]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df2 = pd.DataFrame(a2)
df2

0  1
0  1  2
1  3  4

In [15]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [19]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10, size=(7,2))

array([[1, 0],
       [0, 5],
       [9, 3],
       [5, 5],
       [1, 7],
       [7, 4],
       [5, 1]])

In [20]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3, 5))

array([[0.30611438, 0.00494431, 0.8769836 , 0.22682382, 0.32746187],
       [0.16818208, 0.67974952, 0.47203329, 0.11025808, 0.96368579],
       [0.48973313, 0.27766227, 0.60746133, 0.57275723, 0.72437729]])

In [22]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10, size=(4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?
    Its always the same because numpy.random is pseudo-random and by seeding the random number generator we can guarantee the same results every time.

In [23]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(random_array)

array([1, 2, 3, 4, 5, 7, 9])

In [25]:
# Find the 0'th index of the latest array you created
random_array[0], random_array[0, 0]

(array([9, 1, 3, 7, 4, 9, 3]), 9)

In [26]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [27]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2, :2]

array([[9, 1],
       [5, 3]])

In [37]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array2 = np.random.randint(0, 10, size=(3,5))
ones_array = np.ones((3,5))

In [30]:
# Add the two arrays together
random_array2 + ones_array

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [31]:
# Create another array of ones of shape (5, 3)
ones_array2 = ones_array = np.ones((5, 3))

In [40]:
# Try add the array of ones and the other most recent array together
random_array2 + ones_array2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?
    Matrix addition is done element-wise, which only works if the dimensions match up to each other (or one of them is one) since 3 != 5, the shapes are too different to complete an element-wise equation

How would you fix it?

In [41]:
random_array2 + ones_array2.T

array([[1., 9., 7., 9., 8.],
       [1., 8., 8., 3., 1.],
       [8., 3., 3., 1., 5.]])

In [42]:
# Create another array of ones of shape (3, 5)
ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
# Subtract the new array of ones from the other most recent array
random_array2 - ones_array

array([[-1.,  7.,  5.,  7.,  6.],
       [-1.,  6.,  6.,  1., -1.],
       [ 6.,  1.,  1., -1.,  3.]])

In [45]:
# Multiply the ones array with the latest array
random_array2 * ones_array

array([[0., 8., 6., 8., 7.],
       [0., 7., 7., 2., 0.],
       [7., 2., 2., 0., 4.]])

In [46]:
# Take the latest array to the power of 2 using '**'
random_array2 ** 2

array([[ 0, 64, 36, 64, 49],
       [ 0, 49, 49,  4,  0],
       [49,  4,  4,  0, 16]])

In [47]:
# Do the same thing with np.square()
np.square(random_array2)

array([[ 0, 64, 36, 64, 49],
       [ 0, 49, 49,  4,  0],
       [49,  4,  4,  0, 16]])

In [48]:
# Find the mean of the latest array using np.mean()
np.mean(random_array2)

4.0

In [49]:
# Find the maximum of the latest array using np.max()
np.max(random_array2)

8

In [50]:
# Find the minimum of the latest array using np.min()
np.min(random_array2)

0

In [51]:
# Find the standard deviation of the latest array
np.std(random_array2)

3.141125063837266

In [52]:
# Find the variance of the latest array
np.var(random_array2)

9.866666666666667

In [55]:
# Reshape the latest array to (3, 5, 1)
random_array2.reshape((3, 5, 1))

array([[[0],
        [8],
        [6],
        [8],
        [7]],

       [[0],
        [7],
        [7],
        [2],
        [0]],

       [[7],
        [2],
        [2],
        [0],
        [4]]])

In [56]:
# Transpose the latest array
random_array2.T

array([[0, 0, 7],
       [8, 7, 2],
       [6, 7, 2],
       [8, 2, 0],
       [7, 0, 4]])

What does the transpose do?
    Flips the axes, along with the locations of the individual values.

In [57]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random1 = np.random.randint(10, size=(3,3))
random2 = np.random.randint(10, size=(3,2))

In [58]:
# Perform a dot product on the two newest arrays you created
np.dot(random1, random2)

array([[114, 141],
       [106, 128],
       [ 49,  46]])

In [59]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random11 = np.random.randint(10, size=(4,3))
random12 = np.random.randint(10, size=(4,3))

In [60]:
# Perform a dot product on the two newest arrays you created
np.dot(random11, random12)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [61]:
np.dot(random11, random12.T)

array([[ 63,  30,  23,  36],
       [ 58,  18,  34,  36],
       [ 54,  27,  70,  66],
       [124,  60,  90, 102]])

In [62]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random11.T, random12)

array([[ 93,  63,  52],
       [ 90,  52,  76],
       [ 87,  60, 108]])

Notice how performing a transpose allows the dot product to happen.

Why is this?
    Dot products are a special type of matrix multiplication where the rows of the first matrix are multiplied elementwise against the columns of the second matrix and then summed together to fill a new matrix with the same dimensions as the first dimension of the first matrix and the second dimension of the second matrix. In order for the element-wise multiplication to work in the first place, the rows of the first matrix and the columns of the second matrix must have the same number of elements, so by transposing one of the matrices, the dimensions get flipped so that they match.

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [64]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random111 = np.random.randint(10, size=(2,7))
random112 = np.random.randint(10, size=(2,7))

In [65]:
# Compare the two arrays with '>'
random111 > random112

array([[ True,  True, False,  True,  True,  True, False],
       [ True,  True,  True, False,  True,  True,  True]])

What happens when you compare the arrays with `>`?
    An array of booleans representing the element-wise comparisons with the same shape as the base arrays is returened.

In [66]:
# Compare the two arrays with '>='
random111 >= random112

array([[ True,  True, False,  True,  True,  True, False],
       [ True,  True,  True, False,  True,  True,  True]])

In [67]:
# Find which elements of the first array are greater than 7
random111 > 7

array([[ True,  True, False,  True, False, False, False],
       [False,  True, False, False, False,  True, False]])

In [68]:
# Which parts of each array are equal? (try using '==')
random111 == random112

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [69]:
# Sort one of the arrays you just created in ascending order
np.sort(random111)

array([[2, 3, 5, 6, 8, 8, 8],
       [0, 2, 4, 7, 7, 8, 9]])

In [70]:
# Sort the indexes of one of the arrays you just created
np.argsort(random112)

array([[4, 5, 3, 0, 1, 2, 6],
       [4, 6, 2, 3, 0, 5, 1]], dtype=int64)

In [71]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random1)

0

In [72]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random2)

4

In [73]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random111, axis=1)

array([0, 5], dtype=int64)

In [74]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random112, axis=1)

array([4, 4], dtype=int64)

In [79]:
# Create an array of normally distributed random numbers
np.random.normal(0, 1, 20)

array([ 0.34490234, -0.08008734, -0.24138013,  1.43351549,  1.06579371,
       -2.49875914,  1.48032856,  2.15872852,  1.23177838, -0.21432448,
       -0.68919421,  0.72783311, -0.61906936,  0.35615983, -0.02188087,
        1.21805044, -0.38945802, -0.44280234,  0.37822661,  1.9338398 ])

In [80]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.